# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: lint, format & build
        env:
          CNAME: ${{secrets.CNAME}}
        run: |
          npm run format
          npm run lint
          npm run build
          echo "${CNAME}" >> ./build/CNAME
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
